---
- name: Create a new incident
  servicenow.itsm.incident:
    state: new
    caller: "{{ snow_caller }}"
    short_description: "{{ snow_inc_short_desc }}"
    description: "{{ snow_inc_desc }}"
    impact: "{{ snow_inc_impact }}"
    urgency: "{{ snow_inc_urgency }}"
    other:
      category: "Software"
      assignment_group: "Dd625dccec0a8016700a222a0f7900d06"
  environment:
    SN_HOST: "https://{{ snow_instance }}.service-now.com"
    SN_USERNAME: "{{ snow_username }}"
    SN_PASSWORD: "{{ snow_password }}"
  register: snow_incident

- name: Print incident number
  ansible.builtin.debug:
    var: snow_incident.record.number